services:
  client:
    build: 
      context: .
      dockerfile: Dockerfile.dev # Change this to Dockerfile for production
    container_name: client-imp
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - /usr/src/app/.next
      - /usr/src/app/node_modules
    
  postgres:
    container_name: postgres-db
    image: postgres:alpine
    restart: always
    env_file:
     - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: