# Stage 1: Install dependencies
FROM node:20-alpine

WORKDIR /usr/src/app

COPY package.json package-lock.json ./

COPY prisma ./prisma

RUN npm install --ignore-scripts

COPY . .

CMD [ "npm", "run", "dev:docker" ]