name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js
        uses: actions/setup-node@main
        with:
          node-version: "18"
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build Next.js app
        run: pnpm build
